server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: odilhon1985
    url: jdbc:postgresql://localhost:5432/mohirjpavazifadb
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/application.log